#!/usr/bin/env python
# coding: utf-8

# In[1]:


#rating for things outside and not crowded
outside = 1
#rating for things inside
inside = 2
#rating for things where you get close to people
close = 3
#rating for things where you get close to alot of people
crowded = 4
#rating for things where you get close to alot of people and it isn't the most responsible of atmospheres
packed = 5


def generateLocWeights():
    loc_weights = {}
    loc_weights['advertising'] = inside
    loc_weights['marketing'] = inside
    loc_weights['airport'] = close
    loc_weights['amusement park'] = crowded
    loc_weights['theme park'] = crowded
    loc_weights['assisted living service'] = inside
    loc_weights['assisted'] = inside
    loc_weights['assisted living'] = inside
    loc_weights['home'] = inside
    loc_weights['athletic field'] = outside
    loc_weights['sports field'] = outside
    loc_weights['bagel'] = inside
    loc_weights['donut'] = inside
    loc_weights['bar'] = packed
    loc_weights['alcohol'] = packed
    loc_weights['base'] = inside
    loc_weights['military'] = inside
    loc_weights['beach'] = outside
    loc_weights['beauty'] = close
    loc_weights['hair'] = close
    loc_weights['salon'] = close
    loc_weights['barber'] = close
    loc_weights['beer'] = inside
    loc_weights['wine'] = inside
    loc_weights['spirit'] = inside
    loc_weights['booze'] = inside
    loc_weights['bicycle'] = outside
    loc_weights['bike'] = outside
    loc_weights['cycle'] = outside
    loc_weights['boating'] = outside
    loc_weights['bookstore'] = inside
    loc_weights['book shop'] = inside
    loc_weights['bowling'] = inside
    loc_weights['bowl'] = inside
    loc_weights['bowling alley'] = inside
    loc_weights['brewery'] = inside
    loc_weights['bus station'] = outside
    loc_weights['bus stop'] = outside
    loc_weights['bus'] = outside
    loc_weights['campground'] = outside
    loc_weights['rv park'] = outside
    loc_weights['candy store'] = inside
    loc_weights['candy'] = inside
    loc_weights['candies'] = inside
    loc_weights['confectionary'] = inside
    loc_weights['chocolatier'] = inside
    loc_weights['chocolate'] = inside
    loc_weights['car rental'] = inside
    loc_weights['truck rental'] = inside
    loc_weights['car wash'] = outside
    loc_weights['detail'] = outside
    loc_weights['car detail'] = outside
    loc_weights['car wax'] = outside
    loc_weights['casinos'] = inside
    loc_weights['gaming'] = inside
    loc_weights['cemetery'] = outside
    loc_weights['graveyard'] = outside
    loc_weights['mausoleum'] = outside
    loc_weights['clothing'] = inside
    loc_weights['accessories'] = inside
    loc_weights['apparel'] = inside
    loc_weights['college'] = inside
    loc_weights['university'] = inside
    loc_weights['combat sports'] = inside
    loc_weights['boxing'] = inside
    loc_weights['martial arts'] = inside
    loc_weights['fighting'] = inside
    loc_weights['computer'] = inside
    loc_weights['electronic'] = inside
    loc_weights['contractor'] = inside
    loc_weights['repair'] = inside
    loc_weights['dance'] = inside
    loc_weights['day care'] = inside
    loc_weights['preschool'] = inside
    loc_weights['daycare'] = inside
    loc_weights['child care'] = inside
    loc_weights['department store'] = inside
    loc_weights['big box store'] = inside
    loc_weights['department'] = inside
    loc_weights['dog park'] = outside
    loc_weights['drug services'] = outside
    loc_weights['alcohol services'] = outside
    loc_weights['clinic'] = outside
    loc_weights['dry cleaning'] = inside
    loc_weights['laundry'] = inside
    loc_weights['dry cleaner'] = inside
    loc_weights['laundry service'] = inside
    loc_weights['laundromat'] = inside
    loc_weights['education'] = inside
    loc_weights['school'] = inside
    loc_weights['embassy'] = inside
    loc_weights['foreign'] = inside
    loc_weights['er'] = close
    loc_weights['emergency room'] = close
    loc_weights['fast food'] = inside
    loc_weights['fire stations'] = inside
    loc_weights['fire house'] = inside
    loc_weights['fire department'] = inside
    loc_weights['florist'] = inside
    loc_weights['flowers'] = inside
    loc_weights['flower shop'] = inside
    loc_weights['forest'] = outside
    loc_weights['woods'] = outside
    loc_weights['funeral service'] = inside
    loc_weights['funeral home'] = inside
    loc_weights['furniture'] = inside
    loc_weights['decor'] = inside
    loc_weights['garden'] = outside
    loc_weights['gas station'] = outside
    loc_weights['fuel'] = outside
    loc_weights['gas'] = outside
    loc_weights['gift'] = inside
    loc_weights['novelty'] = inside
    loc_weights['glasses'] = inside
    loc_weights['optical'] = inside
    loc_weights['government agency'] = inside
    loc_weights['gun range'] = outside
    loc_weights['home improvement'] = inside
    loc_weights['repairman'] = inside
    loc_weights['handyman'] = inside
    loc_weights['repair'] = inside
    loc_weights['hospital'] = close
    loc_weights['clinic'] = close
    loc_weights['medical center'] = close
    loc_weights['hotel'] = inside
    loc_weights['motel'] = inside
    loc_weights['houseware'] = inside
    loc_weights['home goods'] = inside
    loc_weights['ice cream parlor'] = inside
    loc_weights['ice cream'] = inside
    loc_weights['insurance'] = inside
    loc_weights['jewelry'] = inside
    loc_weights['watches'] = inside
    loc_weights['accessories'] = inside
    loc_weights['juice bar'] = inside
    loc_weights['smoothie'] = inside
    loc_weights['juice'] = inside
    loc_weights['lake'] = outside
    loc_weights['landmark'] = outside
    loc_weights['legal'] = inside
    loc_weights['lawyer'] = inside
    loc_weights['law'] = inside
    loc_weights['law office'] = inside
    loc_weights['lodging'] = inside
    loc_weights['massage'] = close
    loc_weights['masseuse'] = close
    loc_weights['meat'] = inside
    loc_weights['seafood'] = inside
    loc_weights['butcher'] = inside
    loc_weights['deli'] = inside
    loc_weights['miniature golf'] = outside
    loc_weights['minigolf'] = outside
    loc_weights['mountain'] = outside
    loc_weights['museum'] = inside
    loc_weights['music'] = inside
    loc_weights['show venue'] = inside
    loc_weights['concert'] = inside
    loc_weights['concert hall'] = inside
    loc_weights['natural park'] = outside
    loc_weights['newsstand'] = outside
    loc_weights['newspaper'] = outside
    loc_weights['news'] = outside
    loc_weights['magazine'] = outside
    loc_weights['night club'] = packed
    loc_weights['disco'] = packed
    loc_weights['notary'] = inside
    loc_weights['notary public'] = inside
    loc_weights['nursery'] = inside
    loc_weights['garden'] = inside
    loc_weights['garden center'] = inside
    loc_weights['outdoors'] = outside
    loc_weights['art'] = inside
    loc_weights['painting'] = inside
    loc_weights['park'] = outside
    loc_weights['parking'] = outside
    loc_weights['parking lot'] = outside
    loc_weights['pet'] = inside
    loc_weights['petshop'] = inside
    loc_weights['dog'] = inside
    loc_weights['cat'] = inside
    loc_weights['pharmacy'] = inside
    loc_weights['photo'] = inside
    loc_weights['frame'] = inside
    loc_weights['framing'] = inside
    loc_weights['photography'] = inside
    loc_weights['photo service'] = inside
    loc_weights['physical therapy'] = close
    loc_weights['rehabilitation'] = close
    loc_weights['pizza'] = close
    loc_weights['restaurant'] = close
    loc_weights['police station'] = inside
    loc_weights['law enforcement'] = inside
    loc_weights['port'] = outside
    loc_weights['ferry'] = outside
    loc_weights['post office'] = inside
    loc_weights['mail'] = inside
    loc_weights['professional cleaning'] = inside
    loc_weights['cleaning'] = inside
    loc_weights['train station'] = outside
    loc_weights['rail station'] = outside
    loc_weights['real estate agent'] = inside
    loc_weights['realtor'] = inside
    loc_weights['real estate agency'] = inside
    loc_weights['rest area'] = inside
    loc_weights['rest stop'] = inside
    loc_weights['pitstop'] = inside
    loc_weights['scuba diving'] = outside
    loc_weights['pool'] = outside
    loc_weights['shoes'] = inside
    loc_weights['apparel'] = inside
    loc_weights['shopping center'] = inside
    loc_weights['mall'] = inside
    loc_weights['shopping mall'] = inside
    loc_weights['spa'] = close
    loc_weights['sporting good'] = inside
    loc_weights['sports store'] = inside
    loc_weights['storage'] = outside
    loc_weights['storage facilityt'] = outside
    loc_weights['storage lot'] = outside
    loc_weights['supermarket'] = inside
    loc_weights['groceries'] = inside
    loc_weights['grocery'] = inside
    loc_weights['market'] = inside
    loc_weights['super'] = inside
    loc_weights['swimming pool'] = outside
    loc_weights['swim club'] = outside
    loc_weights['tailor'] = inside
    loc_weights['tattoo'] = close
    loc_weights['tattooing'] = close
    loc_weights['theater'] = inside
    loc_weights['movie theater'] = inside
    loc_weights['cinema'] = inside
    loc_weights['tour'] = inside
    loc_weights['travel agent'] = inside
    loc_weights['tourist information'] = inside
    loc_weights['services'] = inside
    loc_weights['tourism'] = inside
    loc_weights['information'] = inside
    loc_weights['toy'] = inside
    loc_weights['toy shop'] = inside
    loc_weights['utility companies'] = inside
    loc_weights['utilities'] = inside
    loc_weights['utility'] = inside
    loc_weights['public utility'] = inside
    loc_weights['electricity'] = inside
    loc_weights['natural gas'] = inside
    loc_weights['water'] = inside
    loc_weights['sewage'] = inside
    loc_weights['power company'] = inside
    loc_weights['vehicle maintenance'] = inside
    loc_weights['car maintenance'] = inside
    loc_weights['vehicle repair'] = inside
    loc_weights['car repair'] = inside
    loc_weights['winery'] = inside
    loc_weights['vineyard'] = inside
    loc_weights['wine tasting'] = inside
    loc_weights['zoo'] = outside
    loc_weights['aquarium'] = outside
    loc_weights['wildlife sanctuary'] = outside
    return loc_weights


# In[ ]:




